version: "2"
services:
  app:
    container_name: tim-ecp-flask
    build:
      context: .
      dockerfile: Dockerfile
    image: timlimhk/tim-ecp-flask:latest
    ports:
      - "5000:5000"
    environment:
     - service_port=5000
     - log_level=INFO    
     - version=1.0.0
     - git_commit_sha=ac72106
