version: "2"
services:
  app:
    container_name: tim-ecp-pyflask
    build:
      context: .
      dockerfile: Dockerfile
    image: tim-ecp-flask:latest
    ports:
      - "5000:5000"
    environment:
     - service_port=5000
     - log_level=INFO    
     - git_commit_sha=6a6c54303c5
