apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tim-ecp-flask
  name: tim-ecp-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tim-ecp-flask
  template:
    metadata:
      labels:
        app: tim-ecp-flask
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: timlimhk/flask_webapp:0.3
        name: tim-ecp-flask
        env:
        - name: tim-ecp-flask
          value: "app.py"
        # Change to development to enable debug mode
        - name: FLASK_ENV
          value: "development"
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /info
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /info
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tim-ecp-flask
  labels:
    app: tim-ecp-flask
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: http
    targetPort: 5000
  selector:
    app: tim-ecp-flask
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tim-ecp-flask
  annotations:
    # Disables http redirect to https
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: tim-ecp-flask
          servicePort: 5000
