apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tim-ecp-flask
  name: tim-ecp-flask
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tim-ecp-flask
  template:
    metadata:
      labels:
        app: tim-ecp-flask
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: timlimhk/tim-ecp-flask:latest
        name: tim-ecp-flask
        env:
        - name: service_port
          value: "5000"
        - name: log_level
          value: "INFO"
        - name: git_commit_sha
          value: "9898989"
        - name: version
          value: "1.0.3"
        # Change to development to enable debug mode
        - name: FLASK_ENV
          value: "development"
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /info
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /info
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tim-ecp-flask
  labels:
    app: tim-ecp-flask
  namespace: default
spec:
  clusterIP: 10.3.250.188
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30888
    port: 5000
    protocol: TCP
    name: http
    targetPort: 5000
  selector:
    app: tim-ecp-flask
  sessionAffinity: None
  type: LoadBalancer
#---
#apiVersion: networking.k8s.io/v1  # work for minikube
#apiVersion: networking.k8s.io/v1beta1  # for EKS
#apiVersion: networking.k8s.io/v1  # work for GKE 
#kind: Ingress
#metadata:
#  name: tim-ecp-flask
#  namespace: default
#  annotations:
#    # Disables http redirect to https
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
#spec:
#  rules:
##  - host: tim-ecp-flask.info
#  - http:
#     paths:
#     - path: /
#       pathType: Prefix
#       backend:
#         serviceName: tim-ecp-flask # EKS
#         servicePort: 5000  #EKS
##            service:
##              name: tim-ecp-flask
##              port:
##                number: 5000
