#apiVersion: extensions/v1beta1
apiVersion: apps/v1    
kind: Deployment
metadata:
  name: tim-ecp-flask
  labels:
    app: tim-ecp-flask
# namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tim-ecp-flask
  template:
    metadata:
      labels:
        app: tim-ecp-flask
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: tim-ecp-flask
        image:  docker.io/timlimhk/tim-ecp-flask:latest
        ports:
          - name: http  
            containerPort: 5000
            protocol: TCP 
        env:
        - name: service_port
          value: "5000"
        - name: log_level
          value: "INFO"
        - name: git_commit_sha
          value: "9898989"
        - name: version
          value: "1.0.9"
        # Change to development to enable debug mode
        - name: FLASK_ENV
          value: "development"
      imagePullSecrets:
        - name: codefresh-generated-docker.io-dk-repos-default

