apiVersion: v1
kind: Service
metadata:
  name: tim-ecp-flask
  labels:
    app: tim-ecp-flask
  namespace: default
spec:
#  clusterIP: 10.3.250.188
  externalTrafficPolicy: Cluster
  ports:
# - nodePort: 30888
  - port: 5000
    protocol: TCP
    name: http
    targetPort: 5000
  selector:
    app: tim-ecp-flask
  sessionAffinity: None
  type: LoadBalancer
