apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: 2019-01-02T13:59:07Z
  generation: 1
  labels:
    run: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: default
#  resourceVersion: "3857"
# selfLink: /apis/apps/v1/namespaces/default/deployments/tim-ecp-flask
# uid: 92937267-0e96-11e9-86b1-080027785a78
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: tim-ecp-flask
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: tim-ecp-flask
    spec:
      containers:
        - name: {{ .Chart.Name }}
#     - image: timlimhk/tim-ecp-flask:latest
#     - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
#       imagePullPolicy: Always
          imagePullPolicy: {{ .Values.image.pullPolicy }}
#        name: tim-ecp-flask
#       name: {{ .Chart.Name }}
          ports:
            - containerPort: 5000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          {{- if .Values.env }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
