apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  externalTrafficPolicy: Cluster
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetport }}
  selector:
    run: {{ .Chart.Name }}
  sessionAffinity: None
