apiVersion: v1
kind: Service
metadata:
#  name: {{ .Chart.Name }}
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  externalTrafficPolicy: Cluster
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetport }}
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
